services:
  mpd:
    build:
      context: .
      dockerfile: Dockerfile.mpd
    depends_on:
      - snapserver
    volumes:
      - ./music:/var/lib/mpd/music
      - ./playlists:/var/lib/mpd/playlists
      - ./mpd-db:/var/lib/mpd
      - shared-fifo:/shared
    restart: unless-stopped
    ports:
      - '6600:6600'

  snapserver:
    build:
      context: .
      dockerfile: Dockerfile.snapserver
    volumes:
      - ./snapserver.conf:/etc/snapserver.conf
      - shared-fifo:/shared
    restart: unless-stopped
    ports:
      - '1704:1704'
      - '1705:1705'
      - '1780:1780'

  piper:
    build:
      context: .
      dockerfile: Dockerfile.piper
    restart: unless-stopped
    ports:
      - '5000:5000'

  whisper:
    build:
      context: .
      dockerfile: Dockerfile.whisper
      args:
        WHISPER_MODEL: small
    restart: unless-stopped
    ports:
      - '5001:5001'

  svelte-mpd:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MPD_HOST: mpd
        MPD_PORT: 6600
        SNAP_HOST: snapserver
        SNAP_PORT: 1780
        PIPER_HOST: piper
        PIPER_PORT: 5000
        ORIGIN: http://192.168.0.169:3000
        PORT: '3000'
    environment:
      NODE_ENV: production
      MPD_HOST: mpd
      MPD_PORT: '6600'
      SNAP_HOST: snapserver
      SNAP_PORT: '1780'
      PIPER_HOST: piper
      PIPER_PORT: '5000'
      ORIGIN: ${ORIGIN}
      PORT: '3000'
      WHISPER_HOST: whisper
      WHISPER_PORT: '5001'
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ASSISTANT_TOKEN: ${ASSISTANT_TOKEN}
    volumes:
      - ./podcasts-data:/app/data
    depends_on:
      - mpd
      - snapserver
      - piper
      - whisper
    restart: unless-stopped
    privileged: true
    ports:
      - '3000:3000'

volumes:
  shared-fifo:
