FROM python:3.12-slim

ARG PIPER_VOICE=es_ES-davefx-medium

WORKDIR /voices

RUN pip install --no-cache-dir "piper-tts[http]" \
	&& python3 -m piper.download_voices ${PIPER_VOICE}

ENV PIPER_VOICE=${PIPER_VOICE}

EXPOSE 5000

CMD python3 -m piper.http_server -m ${PIPER_VOICE} --host 0.0.0.0 --port 5000
