services:
  svelte-mpd:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MPD_HOST: localhost
        MPD_PORT: 6600
        SNAP_HOST: localhost
        SNAP_PORT: 1780
        ORIGIN: http://192.168.0.169:3000
        PORT: '3000'
    environment:
      NODE_ENV: production
      MPD_HOST: localhost
      MPD_PORT: '6600'
      SNAP_HOST: localhost
      SNAP_PORT: '1780'
      ORIGIN: http://192.168.0.169:3000
      PORT: '3000'
    network_mode: host # shares host network directly; ports mapping is not needed nor supported
    privileged: true
    restart: unless-stopped
